# Generated by Django 3.1.7 on 2021-06-06 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210606_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='address',
            name='object_id',
        ),
        migrations.AddField(
            model_name='machine',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='machine_address', to='users.address'),
        ),
        migrations.AddField(
            model_name='person',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_address', to='users.address'),
        ),
    ]
