# Generated by Django 3.1.7 on 2021-06-06 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_purchase_quantity'),
        ('users', '0005_auto_20210606_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='machine_address', to='users.address'),
        ),
    ]
